[profile.default]
src = 'contracts'
out = 'artifacts_forge'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

# via_ir = true
#no_match_test = "test(Fail)*(Smpl)+.*"

[invariant]
runs = 100